<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerE2rYEFw\srcEnvDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerE2rYEFw/srcEnvDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerE2rYEFw.legacy');

    return;
}

if (!\class_exists(srcEnvDebugProjectContainer::class, false)) {
    \class_alias(\ContainerE2rYEFw\srcEnvDebugProjectContainer::class, srcEnvDebugProjectContainer::class, false);
}

return new \ContainerE2rYEFw\srcEnvDebugProjectContainer(array(
    'container.build_hash' => 'E2rYEFw',
    'container.build_id' => 'afc6ffad',
    'container.build_time' => 1542709187,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerE2rYEFw');
