<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXKGqHLb\srcProdDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXKGqHLb/srcProdDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerXKGqHLb.legacy');

    return;
}

if (!\class_exists(srcProdDebugProjectContainer::class, false)) {
    \class_alias(\ContainerXKGqHLb\srcProdDebugProjectContainer::class, srcProdDebugProjectContainer::class, false);
}

return new \ContainerXKGqHLb\srcProdDebugProjectContainer(array(
    'container.build_hash' => 'XKGqHLb',
    'container.build_id' => '698f2437',
    'container.build_time' => 1542804071,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerXKGqHLb');
