<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container4nMcxd2\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container4nMcxd2/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container4nMcxd2.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\Container4nMcxd2\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \Container4nMcxd2\srcDevDebugProjectContainer(array(
    'container.build_hash' => '4nMcxd2',
    'container.build_id' => '9d8a3517',
    'container.build_time' => 1542481492,
), __DIR__.\DIRECTORY_SEPARATOR.'Container4nMcxd2');
