<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHq9BHPh\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHq9BHPh/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerHq9BHPh.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerHq9BHPh\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerHq9BHPh\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'Hq9BHPh',
    'container.build_id' => '817fed61',
    'container.build_time' => 1543856577,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerHq9BHPh');
